#! /usr/bin/bash
if [ $1 == 'start' ]; then
    sudo systemctl start softconsole
elif [ $1 == 'stop' ]; then
    sudo systemctl stop softconsole
elif [ $1 == 'restart' ]; then
    sudo systemctl restart softconsole
elif [ $1 == 'status' ]; then
    systemctl status softconsole
elif [ $1 == 'journal' ]; then
    journalctl -b --no-hostname -e -u softconsole
elif [ $1 == ps ]; then
    ps agx | fgrep Console
else
    echo ?
fi