#!/bin/bash
cd /home/pi
# Note that we exited to this script from console cleanly
touch cleanexit 
echo "Consoleexit script: " $1 " - " $2 " - " $3 >> log.txt
echo  "Option: " $1 >> log.txt
echo  "Config: " $2 >> log.txt

date >> log.txt
case $1 in
	restart)
		if [ -e usebeta ]
		then
			cd consolebeta
			echo "restart to beta" >> /home/pi/log.txt
		else
			cd consolestable
			echo "restart to stable" >> /home/pi/log.txt
		fi
		pwd >> /home/pi/log.txt
		rm -f /home/pi/cleanexit
		nohup sudo python -u console.py $2 >> /home/pi/log.txt 2>&1 &
        echo "Starting console as process "$! >> /home/pi/log.txt
        echo "Still using rc.local startup mechanism" >> /home/pi/log.txt
        echo "Consider switching to systemd (see usagenotes)" >> /home/pi/log.txt
		;;

	*)
		echo "Unknown exit" >> log.txt
		rm cleanexit
		;;	
esac
