#!/bin/bash
cd /home/pi/
echo "-----Get Current Beta-----" >> /home/pi/log.txt
date >> /home/pi/log.txt
wget https://github.com/kevinkahn/softconsole/archive/currentbeta.tar.gz >>  /home/pi/log.txt

tar -zx < currentbeta.tar.gz >> /home/pi/log.txt
rm -fr consolebeta
mv softconsole-currentbeta consolebeta
rm -f currentbeta.tar.*
echo "-----Done with Fetch -----" /home/pi/log.txt

