#!/bin/bash
cd ~
sudo rm -rf consolestable.old
sudo mv consolestable consolestable.old
sudo mv consolebeta consolestable
sudo echo "beta to stable: " >> log.txt
sudo date >> log.txt
sudo rm -rf log.txt.old
sudo mv log.txt log.txt.old
sudo echo "Beta to Stable" > log.txt
chown pi log.txt
date >> log.txt
echo "==================" >> log.txt

